# (PART) R package {-} 

# Install {#install}

## CRAN 
- https://cran.r-project.org/web/packages/UCSCXenaShiny/index.html

```{r, eval=FALSE}
# Online
install.packages("UCSCXenaShiny")
## or specific repos
install.packages("UCSCXenaShiny", repos = c("https://openbiox.r-universe.dev", "https://cran.r-project.org"))

# Local
install.packages("UCSCXenaShiny_2.0.0.tar.gz", repos = NULL, type="source")
```

- Once the package has been installed successfully, your can check its version:

```{r}
library(UCSCXenaShiny)
packageVersion("UCSCXenaShiny")
```


## Github

```{r, eval=FALSE}
# Online
devtools::install_github("openbiox/UCSCXenaShiny")

# Local
devtools::install_local(path = "UCSCXenaShiny-master.zip")
```


## Conda
```{bash, eval=FALSE}
conda install -c conda-forge r-ucscxenashiny
```

- list all of the versions of r-ucscxenashiny available on your platform:

```{bash, eval=FALSE}
conda search r-ucscxenashiny --channel conda-forge
```


> Note: See other ways of other installations (e.g. Docker, Linux system) from the README interface of [Github project](https://github.com/openbiox/UCSCXenaShiny).  







